emailsend/urls.py
from django.urls import path
from .views import index, success


app_name = 'emailsend'
urlpatterns = [
    path('', index, name='contact'),
    path('success/', success, name='success'),
]

sendemail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emailsend.urls')),
]

emailsend/models.py
from django.db import models
from django.utils import timezone

class MyEmail(models.Model):
    toEmail = models.EmailField(max_length=100, verbose_name='кому отпправляем письмо')
    textmessage = models.CharField(max_length= 250, verbose_name='текст сообщения')
    createdate = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    timedelta = models.PositiveSmallIntegerField(verbose_name='промежуток задержки отправки пиьсма')
    boolsend = models.BooleanField(default=False, verbose_name='Признак отправки')

emailsend/views.py
from django.shortcuts import render
from emailsend.models import MyEmail
from django.core.mail import send_mail, get_connection
from django.http import HttpResponse
import threading
from django.core import mail

from sendemail.settings import DEFAULT_FROM_EMAIL, TIME_ZONE

import datetime

def worker(message, from_email, to_email, id_email):    
    with mail.get_connection() as connection:
        mail.EmailMessage(
            'Subject here', message, from_email, [to_email],
            connection=connection,
        ).send()
  
    update_status = MyEmail.objects.get(id=id_email)
    update_status.boolsend = True
    update_status.save()

def index(request):   
    return render(request, 'index.html')

def success(request):
    
    if request.method == 'POST':

        _toEmail = request.POST['form_mail']
        _textmessage = request.POST['user_message']
        _timedelta = int(request.POST['timedelta'])
        CREATE_DRRM = datetime.datetime.now()

        new_mail = MyEmail.objects.create(toEmail = _toEmail, textmessage = _textmessage, timedelta = _timedelta, createdate = CREATE_DRRM)

        try:
            t = threading.Timer(_timedelta, worker, args=(_textmessage, DEFAULT_FROM_EMAIL, _toEmail, new_mail.id, ))
            t.start()
        except:
            return HttpResponse('Ошибка отправки')
    
    ten_emails = MyEmail.objects.order_by('-id')[:10]
    context = {'ten_emails' : ten_emails,}
    return render(request, 'emails.html', context)

emailsend/templates/base.html
  
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>{% block title %}  {% endblock %}</title>
    <style type="text/css">
        .field_form
        , #content {
            width: 30vw;
        }
        #page_list {
            width: 80vw;
            margin-right: 10vw;
        }
        .btn {
            background:rgb(162, 223, 162);
            margin-top: 5px;
            min-height: 35px;
        }
    </style>
</head>
<body>
    <div id="content">{% block content %}{% endblock %}</div>
    <div id="page_list">{% block page_list %}{% endblock %}</div>
    <div id="footer">
        {% block footer %}
        {% endblock %}
    </div>
</body>
</html>

emailsend/templates/emails.html
{% extends 'base.html' %}

{% block title %} 
Статусы отпраки писем
{% endblock %}

{% block page_list %}
<table border="1">
    <caption>10 последних отправленных писем</caption>
    <tr>
        <th>Кому отправлено</th>
        <th>Содержание пиcьма</th>
        <th>Время старта</th>
        <th>Задержка (сек)</th>
        <th>Статус</th>
    </tr>
    {% for em in ten_emails %}
    <tr>
        <td>{{ em.toEmail }}</td>
        <td>{{ em.textmessage }}</td>

        {% load tz %}
        {% timezone "Europe/Moscow" %}
        <th> {{ em.createdate|date:"d.m.y H:i:s" }} </th>
        {% endtimezone %}
        <th> {{ em.timedelta }} </th>
        
        <td>{% if em.boolsend %}
                Oтправлено
            {% else %}
                В очереди
            {% endif %}
        </td>

    </tr>
    {% endfor %}
</table>
<button class='btn'><a href="{% url 'emailsend:contact' %}">Вернуться на страницу отправки письма</a></button>
{% endblock %}

emailsend/templates/index.html
{% extends 'base.html' %}
{% block title %}
    Форма с параметрами письма
{% endblock %}

{% block content %}
<form action="success/" method="POST">
    {% csrf_token %}
    Your Email:  <input type="email" id="mail" name="form_mail" class='field_form'>
    Time: <input type="number" id="timedelta" name="timedelta" min="0" max="3600">
    <textarea name="user_message" class='field_form'>
        Текст вашего сообщения
    </textarea>
    <button type="submit">Отправить сообщение</button>
</form>
<a href="{% url 'emailsend:success' %}"><button class='btn'>Посмотреть статусы писем</button></a>
{% endblock %}